apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack.yaml
  - traefik.yaml
  - authentik.yaml
  - kyverno.yaml
  - linkerd.yaml
  - prometheus.yaml
  - grafana.yaml
  - victoria-metrics.yaml
  - csi-driver-smb.yaml
  - vikunja.yaml
