apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:tUs6f5GawZM3qSGjJdUyCXQ0jO+JNF7Lr7CDL/3G11Y+HDtMnWTQqw==,iv:sGEaddV+sx4UvMermZih4IjxA3P7g3yAbE8ESQAOEvU=,tag:60OrHV0MH+RZRcBtpocoyA==,type:str]
sops:
    age:
        - recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWFl3c1lKL0REWjNMdGhI
            MjZHWXltQUY1VFcwMUhUTDZyd3o4WHE5bkZRCmNKdUkvMStROTh5cnRvUnpaVSt6
            ZUh2OU8zQnU1Um40SUFNcXR2UU9lN1UKLS0tIEZVMmRLR3pNRnJDMVRGSjF4UHJv
            cGNpVndsWkJULzU2eklnbHJaaHBsajAKcepvfvT6KuQMA4vgjWRqGk5mXWqAbTQY
            bDyNaFkDgJpn24NIspHr+FEIq5O5Pnko6ahCTcttjszwUWU7tCZyKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T12:42:25Z"
    mac: ENC[AES256_GCM,data:JNVuUSBlvzdM2waX4mIN1f1auRrqC6iR6n9G3uBvVZL5Z6cYQ1bZcLieuXlwR0ZC4r95cdaRmg6SY1NhLXP4rsM6ST18nPep+TanOKiaN+k72FwNLdez189g5sYrV19ZaHVwNPURy3CLdB5Inq+8iRMgIDsY2i2hN9i1bog/QHo=,iv:n79d0vLBWBj9fF5yikh2w8GZc6j/rvu9uenA+jwNKHA=,tag:uBIfDp1J3k9xwVMi1mU6yA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
