---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - cert-manager
  - flux-system
  - kyverno
  - kyverno-policies
  - linkerd
  - linkwarden
  - network-policies
  - tailscale
  - traefik
