---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`archive.primed.io`)
      kind: Rule
      middlewares:
        - name: tailscale-ipallowlist
      services:
        - name: paperless-ngx
          port: 8000
  tls:
    secretName: paperless-ngx-tls
