---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - require-labels.yaml
  - disallow-privileged.yaml
  - require-resource-limits.yaml
  - restrict-image-registries.yaml
