---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificates.yaml  # SOPS-encrypted trust anchor (Flux auto-decrypts)
  - identity-issuer.yaml  # SOPS-encrypted issuer certificate (Flux auto-decrypts)
  - crds.yaml
  - helmrelease.yaml
