apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp-password
    namespace: monitoring
stringData:
    smtp-password: ENC[AES256_GCM,data:aE4lEj/GgyY0pTAsH7sfMyTR1pk=,iv:tds4rfYF+fWSf+8Y3NmSgfPYm/XL+HrdkIX261OMm6c=,tag:bVF7KPfFajCHAwX7Y4UKjg==,type:str]
sops:
    age:
        - recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NUg3QzRnTUtNUTBhSHBE
            by9PUmk1ZlpGMlhoOUVPcnlSRW9BWkxMZkE4Clk1cEtsaHBKZlp5b0tkRFFvTWlV
            c3dVckY0RUNscHB4aHZJZkdyZVV5am8KLS0tICs5YVdGMS8zckRydFpUdW1WTzUw
            bGFWbFJwVFpNRTJBdFBDZzE4RmNjVFEKgLW9+7nIueGWCX2BKAsYcLS0UyHBM3l4
            xVei7ouk2iozIaiLCnPEhk1GN2vXhwVyFCCUA3Jgu1POwKPQh8YKIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T15:04:38Z"
    mac: ENC[AES256_GCM,data:HwLcHqxATv/Fu1F4dweR1frdFlrzLgwx9L+/PuIsl7rUbiVl4Y7nKLuC9arEBQ9Qub27yfzl/dvOTH61S9V+KruMB58e8lofEJNOoQ/rUpNvmQHfvscftcoMOM/K+Ewja9BnOKwVxeyPe+dXfkMO9a+N1yeGO1PRFx2aplGfol0=,iv:6E7NfcMKFN1LNjWKmnw2q2p93UMfZA16Cv11OS24N6s=,tag:UYBaMS0BIzhrgOgoosrcKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
