---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-scrape-configs-secret.yaml  # SOPS-encrypted
  - alertmanager-smtp-secret.yaml  # SOPS-encrypted
  - loki-auth-secret.yaml  # SOPS-encrypted
  - prometheus-helmrelease.yaml
  - loki-helmrelease.yaml
  - promtail-helmrelease.yaml
  - alerts.yaml
