apiVersion: v1
kind: Secret
metadata:
    name: prometheus-additional-scrape-configs
    namespace: monitoring
stringData:
    additional-scrape-configs.yaml: ENC[AES256_GCM,data:NlfNT6SDZnU7nFeMI+kOJ23LyCdxT31dRDc6mCO+tQwi9mVCNtzC/AztIoK+hfQTAaRUUtMantiI6I27AtW3z1TgSceRnmJx/d2Rlr2/v/B/62xRc/ptE0sL3YYLqrV4R1gXqOjfkYGXjS803c1p1ScF+aMLj2rlTln9qDHDJVFgSGiLFZTx3/5XoHKKJcuW4MvLYdsglmSggPlIZZOVTbyIqpeeRHBWvrHAoRksFPgD0xXkzbwkSFCvdc7O/DT3NNsJn6jyM9+j4AW7g7L48MgtHFTdH6zrXc4i6rYnSh44Bc3dj4fzbHaljwJ9piFJW2Cp/z1UseRw8S+GobmFglxCZxkVieoSN19G71IoxBR9+JMZCQRqYv94cSNeXKGT+DBs8K820WrPXTR+OzUbT4uFZE3T1tkgLpWW84syW3FbxZaN9YFp/Td+Jkd1otqTkk/oKqQjZuNOOZ7iJcG4pu4NPfJkM275IpRRtithyCUCn2Av0eDKkSxluXaeWuYGnuEq1zjb4wUvzmigG4rmdjEhzzziHR5y44iZYDvQlAo8aP8u9a1k0Db96Y2eZH3rKmc/DMoX5WQo3McAFVxjkcRifwzXU2MI3RzPFmNFw6PsXM6lPzQ6TwtxkHr9n9Oi7yFlY+AXn0nW13hT0IA+4hHm8UshnUCUfozIiY+8L2Ipvcuulq+9yCfeKaQpcfC4QSUZHjuIYTyDDR/xwjZRJvy6ReOTCVnIbkUX9+pJwokH35DU0iBUNktJuO/J1gG6yjD+/N6lffbpjkL9CU3CCKtv6YkRWSFi41EJVWdN/ZXmtLLEfDZsO8tyULVbdoT+a7tkAvQ6k9t8y3w/JHP5CnrxAi2BjsYrJ3tdarUWqBIuU7SN6Ze4bfYjBeqYptlXEaKDD3jGOuXwm72JNZsuJVrBDp4lti3TQkT4,iv:8D9vYZqyy7XgyFMSyrM9PncEDQQuYlWYGl09HVj5KRE=,tag:hpf2t5pVTkzblJpYxY7iHQ==,type:str]
sops:
    age:
        - recipient: age16lss7f9zugtgcnuvmct4evvllznxcewq7cr6vtmpm86v5fx0dvxshxum5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveEJscW1jQWV3M0QrTUh5
            SjRLVkVFRXpXbWs2Q2pQUWhJMlNWcU1FL2pzClU1WFVDcVhkOUFjb2Y3UDRCb0xn
            U0Exa0l4VHJDUzdSQnNtTzRESDBHLzAKLS0tIGQ1S3JVYmFCSUpIR3pmamdvUHcy
            UnZSSlB2MWdxT1NrNndQR1lnd2VVaDAKkDypd/1FB6sIz2S7nOqx0MROiwOfQjNM
            lT1+xPJqYz9EVYnKhftpxwvLsvWacR0MCqDiSASGwXKe65/uxn36/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T14:47:49Z"
    mac: ENC[AES256_GCM,data:6ozTFU1hh+7UaibR/TEjRnP28NVdYSPUMk25DAsSoo8DApRP8jV2mwgupBl+debbE1h25iXYv6Kemw2Akiagmhw2ol1NXNgUMwMD2Gm2vZAimN3OvEziRq84dDu5XCjReouXKrbFCGuQHpJhf1g1IjoIYVsXOnihY+i+x1qJ2f4=,iv:aqGKbxz4nYQ0K8wkzjPWOe275nSKuZ9vjS80MjKQgGw=,tag:Z/mWozFEMTFHiiYMBB4G3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
