---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vikunja
  namespace: vikunja
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tasks.primed.io`)
      kind: Rule
      services:
        - name: vikunja
          port: 3456
  tls:
    secretName: vikunja-tls
