---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vikunja
resources:
  - namespace.yaml
  - secrets.enc.yaml
  - postgres.yaml
  - redis.yaml
  - helmrelease.yaml
  - certificate.yaml
  - ingressroute.yaml
  - network-policies.yaml
