---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - authentik-policies.yaml
  - linkwarden-policies.yaml
  - traefik-policies.yaml
  - system-policies.yaml
  - linkerd-policies.yaml
