---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/production/immich
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-issuers
    - name: traefik
    - name: network-policies
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: postgres
      namespace: immich
    - apiVersion: apps/v1
      kind: StatefulSet
      name: redis
      namespace: immich
    - apiVersion: apps/v1
      kind: Deployment
      name: immich
      namespace: immich
