apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - sources-kustomization.yaml
  - csi-smb-driver-kustomization.yaml
  - priorityclasses-kustomization.yaml
  - cert-manager-kustomization.yaml
  - cert-manager-issuers.yaml
  - traefik-kustomization.yaml
  - tailscale-kustomization.yaml
  - authentik-kustomization.yaml
  - linkwarden-kustomization.yaml
  - nextcloud-kustomization.yaml
  - kyverno-kustomization.yaml
  - kyverno-policies-kustomization.yaml
  - network-policies-kustomization.yaml
  - linkerd-kustomization.yaml
  - monitoring-kustomization.yaml
  - backup-kustomization.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kustomize-controller
        namespace: flux-system
      spec:
        template:
          spec:
            containers:
            - name: manager
              env:
              - name: SOPS_AGE_KEY_FILE
                value: /var/secrets/age.agekey
              volumeMounts:
              - name: sops-age
                mountPath: /var/secrets
            volumes:
            - name: sops-age
              secret:
                secretName: sops-age
    target:
      kind: Deployment
      name: kustomize-controller
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: flux-system
        annotations:
          linkerd.io/inject: enabled
    target:
      kind: Namespace
      name: flux-system
