---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  dependsOn:
    - name: sources
    - name: gateway-api
  # SOPS decryption
  decryption:
    provider: sops
    secretRef:
      name: sops-age
