---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miniflux
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/miniflux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
  dependsOn:
    - name: cert-manager
    - name: traefik
    - name: authentik
    - name: tailscale
    - name: network-policies
  decryption:
    provider: sops
    secretRef:
      name: sops-age
