---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: miniflux
  namespace: miniflux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rss.primed.io`)
      kind: Rule
      middlewares:
        - name: tailscale-ipallowlist
      services:
        - name: miniflux
          port: 8080
  tls:
    secretName: miniflux-tls
