---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux-tailscale
  namespace: miniflux
  annotations:
    tailscale.com/hostname: "miniflux"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - miniflux
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: miniflux
                port:
                  number: 8080
