---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miniflux
resources:
  - namespace.yaml
  - secrets.enc.yaml
  - postgres.yaml
  - deployment.yaml
  - ingress-tailscale.yaml
  - ingressroute.yaml
  - certificate.yaml
  - network-policies.yaml
