apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  # - secrets.enc.yaml  # Temporarily disabled - managing manually due to SOPS issues
  - helmrelease.yaml
  - certificate.yaml
  - ingressroute.yaml
