apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.enc.yaml
  - postgres.yaml
  - redis.yaml
  - media-pvc.yaml
  - helmrelease.yaml
  - certificate.yaml
  - ingressroute.yaml
  - ldap-issuer.yaml
  - ldap-certificate.yaml
  - ldap-outpost.yaml
  - ldap-tailscale-service.yaml
  - authentik-server-direct.yaml
